<?php
defined('ABSPATH') or die;

// common
require_once __DIR__ . "/helpers.php";

// common
require_once __DIR__ . "/post-types.php";
// common
require_once __DIR__ . "/post-types.php";

// ACF
require_once __DIR__ . '/acf/acf.php';
$acfManager = \diis\ACF_Manager::instance();

// theme
require_once __DIR__ . '/enqueues.php';
require_once __DIR__ . '/template-functions.php';
require_once __DIR__ . '/acf/site-options.php';

// AJAX Loadmore
require_once __DIR__ . '/ajax/load-archives.php';
require_once __DIR__ . '/ajax/di-load-shortcode.php';

// misc
// require_once __DIR__ . '/google_tag_manager.php';
require_once __DIR__ . '/products-filter-sort.php';



// Set up theme and post support
function theme_setup() {
	add_theme_support('post-thumbnails');
	add_theme_support('editor-styles');
	add_theme_support('custom-logo', [
		'height'      => 100,
		'width'       => 200,
		'flex-height' => true,
		'flex-width'  => true,
		'header-text' => array( 'site-title', 'site-description' ),
		'unlink-homepage-logo' => true,
	]);
	add_theme_support('menus');
	add_theme_support('title-tag');
	add_theme_support('woocommerce');
	add_theme_support('html5', array(
		'search-form',
		'gallery',
		'caption',
	));

	// Menu locations
	register_nav_menus([
		'main' =>      __( 'main', 'digitalisland' ),
		'footer' => __( 'footer', 'digitalisland '),
	]);

	add_filter('excerpt_length', 'di_excerpt_length', 10, 1);

	add_image_size( 'card-wide',   576, 352 ); // 18:11 aspect-ratio
	add_image_size( 'card-wide-2', 576, 240 ); // 12:5  aspect-ratio

	if( function_exists('acf_add_options_page') ) {

	}


	// add_filter('use_block_editor_for_post_type', 'filter_disable_gutenberg', 10, 2);

	remove_wp_emoji_actions();
}
add_action('after_setup_theme', 'theme_setup');


// Remove WP Emoji
function remove_wp_emoji_actions() {
	remove_action('wp_head', 'print_emoji_detection_script', 7);
	remove_action('wp_print_styles', 'print_emoji_styles');
	remove_action('admin_print_scripts', 'print_emoji_detection_script');
	remove_action('admin_print_styles', 'print_emoji_styles');
}

// Disable Gutenberg for pages
function filter_disable_gutenberg( $bool, $post_type ) {
	if ( $post_type === 'page' ) {
		return false;
	}
	return $bool;
}

function digitalisland_add_style_select_buttons( $buttons ) {
    array_unshift( $buttons, 'styleselect' );
    return $buttons;
}
// Register our callback to the appropriate filter
add_filter( 'mce_buttons_2', 'digitalisland_add_style_select_buttons' );

/**
 * Sets length (by word count) of post excerpts
 *
 * @see wp-includes/formatting.php:3835
 *
 * @param int $length
 */
function di_excerpt_length($length) {
	$length = 30;
	return $length;
}


/**
 * Display an admin notice in wp-admin
 *
 * Note: Messages generated by this function will not be dismissable by user
 *
 * @param string $message
 * @param string $type must be 'info', 'error', 'warning' or 'success'
 */
function di_admin_notice($message, $type="info") {

	if(
		is_admin()
		&& ! wp_doing_ajax()
		&& ! empty($message)
		&& in_array( $type, ['info', 'error', 'warning', 'success'] )
		) {
		$callback = function() use ($message, $type) {
			$class = "notice notice-$type";
			printf( '<div class="%1$s"><p>%2$s</p></div>', esc_attr( $class ), $message );
		};
		add_action( 'admin_notices', $callback );
	}
}
